os: osx
language: swift
osx_image: xcode11.3
before_script:
  - agvtool new-version -all $(date +'%Y.%m.%d.%H.%M')
  - travis/before_script.sh
before_install:
  - gem install xcpretty
  - gem install cocoapods -v '0.32.1'
install:
  - rm -f Podfile.lock
  - travis_wait 10 pod install --silent 
script: - travis/build_script.sh
after_success:
   - gem install jazz
   - make documentation
   - pwd
   - ls -al
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  local-dir: docs
  on:
    branch: develop
