os: osx
language: swift
osx_image: xcode11.3
before_script:
  - agvtool new-version -all $(date +'%Y.%m.%d.%H.%M')
before_install:
  - gem install xcpretty
  - gem install cocoapods -v '0.32.1'
install:
  - rm -f Podfile.lock
  - travis_wait 10 pod install --silent 
script:
  - xcodebuild clean build -sdk iphonesimulator -workspace TDT-project.xcworkspace -scheme TDTTests CODE_SIGNING_REQUIRED=NO | xcpretty -s && exit ${PIPESTATUS[0]}
after_success:
   bash <(curl -s https://codecov.io/bash)
